#**LAB 02**



---


---










# **Task 1: Vectors**






---


•	Create a vector containing the ages of 6 people of your choice.

•	Print the vector's shape, dimensions, and data type.

•	Create a second vector of the same size representing "years until retirement" (65 − age) without using a loop.

•	Find and print the average age using a NumPy function (do not calculate it manually).



In [112]:

import numpy as np
#Create the age vector
ages = np.array([25, 30, 45, 22, 50, 35])

In [113]:
#Shape, dimensions and data type
print(f"Ages vector: {ages}")
print(f"Shape of ages vector: {ages.shape}")
print(f"Dimensions of ages vector: {ages.ndim}")
print(f"Data type of ages vector: {ages.dtype}")

Ages vector: [25 30 45 22 50 35]
Shape of ages vector: (6,)
Dimensions of ages vector: 1
Data type of ages vector: int64


In [114]:
#Years until retirement
years_until_retirement = 65 - ages
print(f"Years until retirement vector: {years_until_retirement}")

Years until retirement vector: [40 35 20 43 15 30]


In [115]:

#Average age
average_age = np.mean(ages)
print(f"Average age: {average_age}")

Average age: 34.5




---


# **Task 2: Matrices**


---


•	Create a 4×3 matrix representing the sales (in units) of 4 products across 3 months.

•	Print the matrix's shape and total number of elements.

•	Create a second matrix of the same shape filled entirely with zeros using a NumPy function (not by typing zeros manually).

•	Replace the zero matrix's second row with the values [10, 20, 30] using indexing (not by recreating the matrix).


In [116]:
import numpy as np
#Create the sales matrix
sales_matrix = np.array([
    [100, 120, 150],
    [ 80,  90, 110],
    [130, 140, 160],
    [ 70,  75,  85]
])

print("Sales Matrix:")
print(sales_matrix)

Sales Matrix:
[[100 120 150]
 [ 80  90 110]
 [130 140 160]
 [ 70  75  85]]


In [117]:
# Shape and total number of elements
print(f"\nShape of sales matrix: {sales_matrix.shape}")
print(f"Total number of elements in sales matrix: {sales_matrix.size}")


Shape of sales matrix: (4, 3)
Total number of elements in sales matrix: 12


In [118]:
#Create zero matrix
zero_matrix = np.zeros_like(sales_matrix)
print("\nInitial Zero Matrix:")
print(zero_matrix)


Initial Zero Matrix:
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [119]:
#Replace second row
zero_matrix[1, :] = [10, 20, 30]
print("\nZero Matrix after updating second row:")
print(zero_matrix)


Zero Matrix after updating second row:
[[ 0  0  0]
 [10 20 30]
 [ 0  0  0]
 [ 0  0  0]]




---


# **Task 3: Addition & Subtraction**


---


•	Create two 3×3 matrices representing the marks of 3 students in 3 subjects for Term 1 and Term 2.

•	Calculate the total combined marks (Term 1 + Term 2) for each student in each subject.

•	Calculate the improvement (Term 2 − Term 1) for each student in each subject.

•	Using the improvement matrix, identify (through code, not by manually reading) which student had the highest total improvement across all subjects.


In [120]:
#Term 1 marks
students = np.array(["Nimra", "Ayesha", "Fatima"])

term1 = np.array([
    [70, 75, 80],
    [65, 80, 72],
    [85, 78, 88]
])

print("Term 1 Marks:")
print(term1)


Term 1 Marks:
[[70 75 80]
 [65 80 72]
 [85 78 88]]


In [121]:
#Term 2 marks
term2 = np.array([
    [78, 82, 85],
    [75, 85, 80],
    [90, 84, 92]
])

print("Term 2 Marks:")
print(term2)


Term 2 Marks:
[[78 82 85]
 [75 85 80]
 [90 84 92]]


In [122]:
#Total combined marks
total_marks = term1 + term2

print("Total Combined Marks:")
print(total_marks)


Total Combined Marks:
[[148 157 165]
 [140 165 152]
 [175 162 180]]


In [123]:
#Improvement
improvement = term2 - term1

print("Improvement Matrix:")
print(improvement)


Improvement Matrix:
[[ 8  7  5]
 [10  5  8]
 [ 5  6  4]]


In [124]:
#Student with highest total improvement

total_improvement = np.sum(improvement, axis=1)

print("Total Improvement:")
print(total_improvement)

highest_index = np.argmax(total_improvement)

print("Student with highest total improvement:")
print(students[highest_index])


Total Improvement:
[20 23 15]
Student with highest total improvement:
Ayesha




---


# **Task 4: Dot Product**


---


•	Create a vector of 4 item prices and a vector of the quantities purchased for each item.

•	Calculate the total bill using the dot product (not by multiplying and adding manually).

•	Create a 2×4 matrix representing quantities purchased by 2 different customers, then calculate the total bill for both customers using a single dot product operation.

•	Explain (in a comment in your code) why the shapes of the two arrays had to match a specific way for the dot product to work.


In [125]:
import numpy as np
#Prices and quantities
prices = np.array([10.5, 5.2, 20.0, 1.75])
quantities = np.array([3, 10, 2, 5])

print(f"Item Prices: {prices}")
print(f"Quantities Purchased: {quantities}")

Item Prices: [10.5   5.2  20.    1.75]
Quantities Purchased: [ 3 10  2  5]


In [126]:
#Total bill using dot product
total_bill = np.dot(prices, quantities)
print(f"\nTotal bill for single customer: ${total_bill:.2f}")


Total bill for single customer: $132.25


In [127]:
#Quantities of two customers
quantities_customers = np.array([
    [3, 10, 2, 5],
    [1, 5, 3, 2]
])

print("\nQuantities purchased by two customers:")
print(quantities_customers)

#Bills for both customers
total_bills_customers = np.dot(quantities_customers, prices)
print(f"\nTotal bills for customers: ${total_bills_customers[0]:.2f}, ${total_bills_customers[1]:.2f}")


Quantities purchased by two customers:
[[ 3 10  2  5]
 [ 1  5  3  2]]

Total bills for customers: $132.25, $100.00


In [128]:
# customer_quantities has shape (2, 4)
# prices has shape (4,)
#
# The 4 columns of customer_quantities must match
# the 4 elements in the prices vector.
#
# Therefore, the dot product produces one total bill
# for each of the 2 customers.




---


# **Task 5: Reshaping**

---


•	Create a 1D array of 12 numbers representing hours studied by a student over 12 days.

•	Reshape this array into a 3×4 matrix (3 weeks... wait, adjust: 4 rows × 3 days) representing 4 weeks of a 3-day study plan.

•	Reshape the same original array into a different valid shape (not 4×3), and print both reshaped versions.

•	Try reshaping the array into a shape that is not possible (e.g., 5×3) and note down the error message you get.


In [129]:
import numpy as np
#Create 1D array
hours_studied_12_days = np.array([2, 3, 1, 4, 2, 5, 3, 1, 4, 2, 3, 5])

print(f"Original 1D array of hours studied: {hours_studied_12_days}")
print(f"Shape of original array: {hours_studied_12_days.shape}")

Original 1D array of hours studied: [2 3 1 4 2 5 3 1 4 2 3 5]
Shape of original array: (12,)


In [130]:
 #Reshape into 4×3
study_plan_4x3 = hours_studied_12_days.reshape(4, 3)
print("\nReshaped into 4x3 matrix (4 weeks, 3 days/week):")
print(study_plan_4x3)
print(f"Shape of 4x3 matrix: {study_plan_4x3.shape}")


Reshaped into 4x3 matrix (4 weeks, 3 days/week):
[[2 3 1]
 [4 2 5]
 [3 1 4]
 [2 3 5]]
Shape of 4x3 matrix: (4, 3)


In [131]:
#Reshape into another valid shape
study_plan_6x2 = hours_studied_12_days.reshape(6, 2)
print("\nReshaped into 6x2 matrix (e.g., 6 fortnights, 2 days/fortnight):")
print(study_plan_6x2)
print(f"Shape of 6x2 matrix: {study_plan_6x2.shape}")


Reshaped into 6x2 matrix (e.g., 6 fortnights, 2 days/fortnight):
[[2 3]
 [1 4]
 [2 5]
 [3 1]
 [4 2]
 [3 5]]
Shape of 6x2 matrix: (6, 2)


In [132]:
#Invalid reshape
try:
    invalid_reshape = hours_studied_12_days.reshape(5, 3)
    print("This line should not be reached.")
except ValueError as e:
    print(f"\nAttempting invalid reshape (5x3) resulted in an error:")
    print(f"Error message: {e}")
    print("Explanation: A ValueError occurred because the total number of elements in the original array (12) must be equal to the product of the dimensions of the new shape (5 * 3 = 15). Since 12 != 15, the reshape operation is not possible.")


Attempting invalid reshape (5x3) resulted in an error:
Error message: cannot reshape array of size 12 into shape (5,3)
Explanation: A ValueError occurred because the total number of elements in the original array (12) must be equal to the product of the dimensions of the new shape (5 * 3 = 15). Since 12 != 15, the reshape operation is not possible.




---


# **Task 6: Indexing**

---


•	Create a 5×5 matrix filled with random integers between 1 and 50.

•	Access and print the element in the 3rd row and 4th column using indexing.

•	Access and print the last row and the last column using negative indexing.

•	Change the value of the element at position (0,0) to 999 using indexing, then print the updated matrix.


In [133]:
import numpy as np
#Create random matrix
np.random.seed(42)
matrix_5x5 = np.random.randint(1, 51, size=(5, 5))
print("Original 5x5 Matrix:")
print(matrix_5x5)

Original 5x5 Matrix:
[[39 29 15 43  8]
 [21 39 19 23 11]
 [11 24 36 40 24]
 [ 3 22  2 24 44]
 [30 38  2 21 33]]


In [134]:
#Access 3rd row and 4th column
element_3rd_row_4th_col = matrix_5x5[2, 3]
print(f"\nElement in 3rd row, 4th column: {element_3rd_row_4th_col}")


Element in 3rd row, 4th column: 40


In [135]:
#Last row and last column
last_row = matrix_5x5[-1, :]
last_column = matrix_5x5[:, -1]
print(f"\nLast row: {last_row}")
print(f"Last column: {last_column}")


Last row: [30 38  2 21 33]
Last column: [ 8 11 24 44 33]


In [136]:
#Change position (0,0)
matrix_5x5[0, 0] = 999
print("\nMatrix after changing element at (0,0) to 999:")
print(matrix_5x5)


Matrix after changing element at (0,0) to 999:
[[999  29  15  43   8]
 [ 21  39  19  23  11]
 [ 11  24  36  40  24]
 [  3  22   2  24  44]
 [ 30  38   2  21  33]]




---


# **Task 7: Slicing**

---


•	Create a 6×6 matrix filled with numbers from 1 to 36 (in order).

•	Extract the top-left 3×3 sub-matrix using slicing.

•	Extract every alternate row and every alternate column from the full matrix using step slicing.

•	Extract the last 2 rows and last 2 columns together as a single sub-matrix.


In [137]:
import numpy as np
#Create matrix
matrix_6x6 = np.arange(1, 37).reshape(6, 6)
print("Original 6x6 Matrix:")
print(matrix_6x6)

Original 6x6 Matrix:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [138]:
 #Top-left 3×3
top_left_3x3 = matrix_6x6[0:3, 0:3]
print("\nTop-left 3x3 sub-matrix:")
print(top_left_3x3)


Top-left 3x3 sub-matrix:
[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]


In [139]:
#Alternate rows and columns
alternate_rows_cols = matrix_6x6[::2, ::2]
print("\nEvery alternate row and column:")
print(alternate_rows_cols)


Every alternate row and column:
[[ 1  3  5]
 [13 15 17]
 [25 27 29]]


In [140]:
#Last 2 rows and columns
last_2_rows_cols = matrix_6x6[-2:, -2:]
print("\nLast 2 rows and last 2 columns (sub-matrix):")
print(last_2_rows_cols)


Last 2 rows and last 2 columns (sub-matrix):
[[29 30]
 [35 36]]




---


# **Task 8: Random Matrices**





---


•	Set a random seed of your choice, then generate a 3×3 matrix of random decimal values between 0 and 1.

•	Generate a 3×3 matrix of random integers between 10 and 100.

•	Generate a 4×4 matrix using the standard normal distribution (values can be negative).

•	Without changing the seed, run your random decimal generation code (part 1) twice and compare, explain in a comment why both outputs are identical.


In [141]:
#Set seed and generate decimal matrix
np.random.seed(42)

decimal_matrix = np.random.rand(3, 3)

print("Random Decimal Matrix:")
print(decimal_matrix)

Random Decimal Matrix:
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


In [142]:
#Random integers
integer_matrix = np.random.randint(10, 101, size=(3, 3))

print("Random Integer Matrix:")
print(integer_matrix)

Random Integer Matrix:
[[33 12 31]
 [62 11 97]
 [39 47 11]]


In [143]:
#Standard normal distribution
normal_matrix = np.random.randn(4, 4)

print("Standard Normal Matrix:")
print(normal_matrix)

Standard Normal Matrix:
[[-0.46341769 -0.46572975  0.24196227 -1.91328024]
 [-1.72491783 -0.56228753 -1.01283112  0.31424733]
 [-0.90802408 -1.4123037   1.46564877 -0.2257763 ]
 [ 0.0675282  -1.42474819 -0.54438272  0.11092259]]


In [144]:
#Compare decimal matrices
np.random.seed(42)
decimal_matrix_1 = np.random.rand(3, 3)

np.random.seed(42)
decimal_matrix_2 = np.random.rand(3, 3)

print("First Matrix:")
print(decimal_matrix_1)

print("\nSecond Matrix:")
print(decimal_matrix_2)

print("\nAre both matrices identical?")
print(np.array_equal(decimal_matrix_1, decimal_matrix_2))

# Both outputs are identical because the same random seed
# starts the random number generator from the same state.

First Matrix:
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]

Second Matrix:
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]

Are both matrices identical?
True




---


# **Task 9: Transpose**


---


•	Create a 3×5 matrix representing 3 employees' performance scores across 5 months.

•	Transpose the matrix and print its new shape.

•	Verify programmatically (using code, not by manual inspection) that transposing the matrix twice gives back the original matrix.

•	Create a 4×2 and a 3×2 matrix, and use transpose on one of them so that a dot product between the two becomes possible; then perform the dot product.


In [145]:
import numpy as np
#Create 3×5 matrix
performance = np.array([
    [80, 82, 85, 88, 90],   # Nimra
    [75, 78, 80, 84, 87],   # Ayesha
    [90, 88, 92, 94, 95]    # Fatima
])

print("Performance Matrix:")
print(performance)

print("Original Shape:")
print(performance.shape)

Performance Matrix:
[[80 82 85 88 90]
 [75 78 80 84 87]
 [90 88 92 94 95]]
Original Shape:
(3, 5)


In [146]:
#Transpose
transposed_scores = performance_scores.T

print("\nTransposed Performance Scores Matrix (5x3):")
print(transposed_scores)
print(f"New Shape: {transposed_scores.shape}")


Transposed Performance Scores Matrix (5x3):
[[80 75 90]
 [85 70 88]
 [78 82 95]
 [92 79 85]
 [88 90 91]]
New Shape: (5, 3)


In [147]:
#Verify transpose twice
double_transposed_scores = transposed_scores.T

print("\nMatrix after transposing twice:")
print(double_transposed_scores)

is_original = np.array_equal(performance_scores, double_transposed_scores)
print(f"Is the double-transposed matrix identical to the original? {is_original}")


Matrix after transposing twice:
[[80 85 78 92 88]
 [75 70 82 79 90]
 [90 88 95 85 91]]
Is the double-transposed matrix identical to the original? True


In [148]:
#Create 4×2 and 3×2 matrices
matrix_A = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8]
])

matrix_B = np.array([
    [10, 20],
    [30, 40],
    [50, 60]
])

print("\nMatrix A (4x2):")
print(matrix_A)
print(f"Shape A: {matrix_A.shape}")

print("\nMatrix B (3x2):")
print(matrix_B)
print(f"Shape B: {matrix_B.shape}")



Matrix A (4x2):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Shape A: (4, 2)

Matrix B (3x2):
[[10 20]
 [30 40]
 [50 60]]
Shape B: (3, 2)


In [149]:

#Transpose and dot product
matrix_B_transposed = matrix_B.T
print("\nMatrix B Transposed (2x3):")
print(matrix_B_transposed)
print(f"Shape B Transposed: {matrix_B_transposed.shape}")

dot_product_result = np.dot(matrix_A, matrix_B_transposed)

print("\nResult of dot product (Matrix A . Matrix B Transposed):")
print(dot_product_result)
print(f"Result Shape: {dot_product_result.shape}")


Matrix B Transposed (2x3):
[[10 30 50]
 [20 40 60]]
Shape B Transposed: (2, 3)

Result of dot product (Matrix A . Matrix B Transposed):
[[ 50 110 170]
 [110 250 390]
 [170 390 610]
 [230 530 830]]
Result Shape: (4, 3)
